[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
domain = { path = "../domain" }
parking_lot = "0.12.3"
rusqlite = { version = "0.37.0", features = ["bundled", "chrono"] }
rusqlite_migration = "2.3.0"
thiserror = "2.0.12"
